version: '2'
services:
  nginx:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      lagoon.type: nginx
    volumes:
      - .:/app:delegated
    ports:
      - "8080:8080"
    environment:
      - AMAZEEIO_URL=petsofamazee.docker.amazee.io
networks:
  amazeeio-network:
    external: true